#!/usr/bin/env ruby

# Not sure that the list of services & regions is available in the JS SDK, but
# it is in ruby.
require 'aws-sdk'
require 'json'

regions_data = Aws.partition('aws').services.map do |s|
  [ s.name, s.regions.to_a.sort ]
end.sort_by(&:first).to_h

IO.write("regions-data.json", JSON.pretty_generate(regions_data))
